# Generated by Django 6.0.5 on 2026-05-14 15:53

import django.db.models.deletion
import django.utils.timezone
import web.models.character
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile",
            field=models.TextField(default="宝宝懒，什么都没有留下。", max_length=500),
        ),
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "photo",
                    models.ImageField(upload_to=web.models.character.photo_upload_path),
                ),
                ("profile", models.TextField(max_length=100000)),
                (
                    "background_image",
                    models.ImageField(
                        upload_to=web.models.character.background_image_upload_path
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "update_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.userprofile",
                    ),
                ),
            ],
        ),
    ]
