# Generated by Django 6.0.5 on 2026-05-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="input",
            field=models.TextField(max_length=10000),
        ),
    ]
